
version: '3.8'

services:
  strapi:
    build:
      context: ./strapi-server
      dockerfile: Dockerfile
    ports:
      - "1337:1337"
    depends_on:
      - strapi-db
    environment:
      - HOST=0.0.0.0
      - PORT=1337
      - APP_KEYS=toBeModified1,toBeModified2
      - API_TOKEN_SALT=tobemodified
      - ADMIN_JWT_SECRET=tobemodified
      - TRANSFER_TOKEN_SALT=tobemodified
      - JWT_SECRET=tobemodified
      - DATABASE_CLIENT=postgres
      - DATABASE_HOST=strapi-db
      - DATABASE_PORT=5432
      - DATABASE_NAME=strapi
      - DATABASE_USERNAME=strapi
      - DATABASE_PASSWORD=strapi
      - DATABASE_SSL=false
    volumes:
      - ./strapi-server:/app
      - /app/node_modules

  strapi-db:
    image: postgres:14-alpine
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_USER=strapi
      - POSTGRES_PASSWORD=strapi
      - POSTGRES_DB=strapi
    volumes:
      - strapi-data:/var/lib/postgresql/data

volumes:
  strapi-data:
    driver: local
