volumes:
  medusa-db-data:
  medusa-redis-data:
  strapi-data:

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - medusa
      - strapi
