# Development override for shared-auth-middleware
services:
  shared-auth-middleware:
    build:
      target: development
    environment:
      NODE_ENV: development
      LOG_LEVEL: debug
    volumes:
      # Mount source code for hot reload
      - .:/app
      - /app/node_modules
    command: ["npm", "run", "start:dev"]
    stdin_open: true
    tty: true

  # Development tools
  redis:
    image: redis:7-alpine
    container_name: shared-auth-redis
    ports:
      - "6379:6379"
    networks:
      - shared-auth-network
    profiles:
      - with-redis

  # Database for development (if needed)
  postgres:
    image: postgres:15-alpine
    container_name: shared-auth-postgres
    environment:
      POSTGRES_DB: shared_auth
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: auth_password
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - shared-auth-network
    profiles:
      - with-db

volumes:
  postgres_data:
    driver: local