services:
  shared-auth-middleware:
    build:
      context: shared-auth-middleware
      dockerfile: Dockerfile
      target: production
    container_name: shared-auth-middleware
    environment:
      JWT_SECRET: ${JWT_SECRET}
      MEDUSA_URL: ${MEDUSA_URL:-http://medusa:9000}
      STRAPI_URL: ${STRAPI_URL:-http://strapi:1337}
      PORT: 3000
      NODE_ENV: ${NODE_ENV:-production}
      TOKEN_EXPIRY: ${TOKEN_EXPIRY:-24h}
      LOG_LEVEL: ${LOG_LEVEL:-info}
    ports:
      - "${SHARED_AUTH_PORT:-3000}:3000"
    networks:
      - unified-auth-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s