services:
  medusa:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    depends_on:
      - medusa-db
      - medusa-redis
    environment:
      - DATABASE_URL=postgres://marketplace:super-secure-password@medusa-db:5432/goiaba_db?sslmode=disable
      - REDIS_URL=redis://medusa-redis:6379
      - NODE_ENV=development
      - JWT_SECRET=supersecret
      - COOKIE_SECRET=supersecret
      - DB_NAME=goiaba_db
      - STORE_CORS=http://localhost:8000,https://docs.medusajs.com,http://localhost:8100,http://localhost:46247/,http://localhost:5173
      - ADMIN_CORS=http://localhost:5173,http://localhost:9000,https://docs.medusajs.com,http://localhost:8100,http://localhost:46247/,http://localhost:5173
      - AUTH_CORS=http://localhost:5173,http://localhost:9000,https://docs.medusajs.com,http://localhost:8100,http://localhost:46247/,http://localhost:5173
      - API_KEY=noop
      - VITE_BACKEND_URL=http://localhost:9000
      - MEDUSA_PUBLISHABLE_API_KEY=pk_3a082fac8795505e1d19814c38c9bbc92f233d9cd93b3caeaab601eb7e802af6
    volumes:
      - .:/app
      - /app/node_modules

  medusa-db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=marketplace
      - POSTGRES_PASSWORD=super-secure-password
      - POSTGRES_DB=goiaba_db
    volumes:
      - medusa-db-data:/var/lib/postgresql/data

  medusa-redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - medusa-redis-data:/data

volumes:
  medusa-db-data:
    driver: local
  medusa-redis-data:
    driver: local
